[2024-11-04T23:53:40.791+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-04T23:53:40.809+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketvol.tmp_move_AAPL manual__2024-11-04T23:53:26.624508+00:00 [queued]>
[2024-11-04T23:53:40.818+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketvol.tmp_move_AAPL manual__2024-11-04T23:53:26.624508+00:00 [queued]>
[2024-11-04T23:53:40.819+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2024-11-04T23:53:40.834+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): tmp_move_AAPL> on 2024-11-04 23:53:26.624508+00:00
[2024-11-04T23:53:40.841+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=15853) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-04T23:53:40.843+0000] {standard_task_runner.py:72} INFO - Started process 15857 to run task
[2024-11-04T23:53:40.844+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'marketvol', 'tmp_move_AAPL', 'manual__2024-11-04T23:53:26.624508+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/Airflow_Miniproj.py', '--cfg-path', '/tmp/tmp008r231t']
[2024-11-04T23:53:40.846+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask tmp_move_AAPL
[2024-11-04T23:53:40.897+0000] {task_command.py:467} INFO - Running <TaskInstance: marketvol.tmp_move_AAPL manual__2024-11-04T23:53:26.624508+00:00 [running]> on host 2e0e50a1433f
[2024-11-04T23:53:41.019+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Margaret' AIRFLOW_CTX_DAG_ID='marketvol' AIRFLOW_CTX_TASK_ID='tmp_move_AAPL' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T23:53:26.624508+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-04T23:53:26.624508+00:00'
[2024-11-04T23:53:41.021+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-04T23:53:41.022+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-04T23:53:41.024+0000] {logging_mixin.py:190} INFO - Current task name:tmp_move_AAPL state:running start_date:2024-11-04 23:53:40.810040+00:00
[2024-11-04T23:53:41.024+0000] {logging_mixin.py:190} INFO - Dag name:marketvol and current dag run status:running
[2024-11-04T23:53:41.025+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-04T23:53:41.027+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-04T23:53:41.028+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mv ./AAPL_data.csv /tmp/data/2024-11-04/']
[2024-11-04T23:53:41.042+0000] {subprocess.py:86} INFO - Output:
[2024-11-04T23:53:41.047+0000] {subprocess.py:93} INFO - mv: cannot stat './AAPL_data.csv': No such file or directory
[2024-11-04T23:53:41.049+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-04T23:53:41.067+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-04T23:53:41.086+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-04T23:53:41.087+0000] {logging_mixin.py:190} INFO - Task start:2024-11-04 23:53:40.810040+00:00 end:2024-11-04 23:53:41.085339+00:00 duration:0.275299
[2024-11-04T23:53:41.092+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): tmp_move_AAPL> dag:<DAG: marketvol> dagrun:<DagRun marketvol @ 2024-11-04 23:53:26.624508+00:00: manual__2024-11-04T23:53:26.624508+00:00, state:running, queued_at: 2024-11-04 23:53:26.683633+00:00. externally triggered: True>
[2024-11-04T23:53:41.093+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2024-11-04T23:53:41.098+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=marketvol, task_id=tmp_move_AAPL, run_id=manual__2024-11-04T23:53:26.624508+00:00, execution_date=20241104T235326, start_date=20241104T235340, end_date=20241104T235341
[2024-11-04T23:53:41.143+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-04T23:53:41.145+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task tmp_move_AAPL (Bash command failed. The command returned a non-zero exit code 1.; 15857)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-04T23:53:41.180+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-04T23:53:41.197+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
