[2024-11-04T23:58:45.179+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-04T23:58:45.206+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketvol.tmp_move_TSLA manual__2024-11-04T23:53:26.624508+00:00 [queued]>
[2024-11-04T23:58:45.219+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketvol.tmp_move_TSLA manual__2024-11-04T23:53:26.624508+00:00 [queued]>
[2024-11-04T23:58:45.220+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 3
[2024-11-04T23:58:45.248+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): tmp_move_TSLA> on 2024-11-04 23:53:26.624508+00:00
[2024-11-04T23:58:45.256+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=15926) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-04T23:58:45.258+0000] {standard_task_runner.py:72} INFO - Started process 15931 to run task
[2024-11-04T23:58:45.260+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'marketvol', 'tmp_move_TSLA', 'manual__2024-11-04T23:53:26.624508+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/Airflow_Miniproj.py', '--cfg-path', '/tmp/tmp0hodlny5']
[2024-11-04T23:58:45.262+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask tmp_move_TSLA
[2024-11-04T23:58:45.337+0000] {task_command.py:467} INFO - Running <TaskInstance: marketvol.tmp_move_TSLA manual__2024-11-04T23:53:26.624508+00:00 [running]> on host 2e0e50a1433f
[2024-11-04T23:58:45.492+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Margaret' AIRFLOW_CTX_DAG_ID='marketvol' AIRFLOW_CTX_TASK_ID='tmp_move_TSLA' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T23:53:26.624508+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-04T23:53:26.624508+00:00'
[2024-11-04T23:58:45.493+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-04T23:58:45.495+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-04T23:58:45.496+0000] {logging_mixin.py:190} INFO - Current task name:tmp_move_TSLA state:running start_date:2024-11-04 23:58:45.207237+00:00
[2024-11-04T23:58:45.496+0000] {logging_mixin.py:190} INFO - Dag name:marketvol and current dag run status:running
[2024-11-04T23:58:45.497+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-04T23:58:45.499+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-04T23:58:45.500+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mv ./TSLA_data.csv /tmp/data/2024-11-04/']
[2024-11-04T23:58:45.516+0000] {subprocess.py:86} INFO - Output:
[2024-11-04T23:58:45.522+0000] {subprocess.py:93} INFO - mv: cannot stat './TSLA_data.csv': No such file or directory
[2024-11-04T23:58:45.523+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-04T23:58:45.544+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-04T23:58:45.558+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-04T23:58:45.559+0000] {logging_mixin.py:190} INFO - Task start:2024-11-04 23:58:45.207237+00:00 end:2024-11-04 23:58:45.557319+00:00 duration:0.350082
[2024-11-04T23:58:45.559+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): tmp_move_TSLA> dag:<DAG: marketvol> dagrun:<DagRun marketvol @ 2024-11-04 23:53:26.624508+00:00: manual__2024-11-04T23:53:26.624508+00:00, state:running, queued_at: 2024-11-04 23:53:26.683633+00:00. externally triggered: True>
[2024-11-04T23:58:45.560+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2024-11-04T23:58:45.561+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=marketvol, task_id=tmp_move_TSLA, run_id=manual__2024-11-04T23:53:26.624508+00:00, execution_date=20241104T235326, start_date=20241104T235845, end_date=20241104T235845
[2024-11-04T23:58:45.589+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-04T23:58:45.590+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task tmp_move_TSLA (Bash command failed. The command returned a non-zero exit code 1.; 15931)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-04T23:58:45.635+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-04T23:58:45.687+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-04T23:58:45.691+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
